dataset_params:
  im_path: '/kaggle/input/dataset'
  im_channels: 3
  im_size: 256  # 保持原分辨率
  name: 'doppler'

diffusion_params:
  num_timesteps: 1000
  beta_start: 0.0015
  beta_end: 0.0195

ldm_params:
  down_channels: [128, 256, 256, 256]  # 保持通道配置
  mid_channels: [256, 256]
  down_sample: [True, True, False]
  attn_down: [True, True, True]  # 在所有层启用注意力
  time_emb_dim: 256
  norm_channels: 64
  num_heads: 16  # 增加注意力头数量，确保通道数能被头数整除
  conv_out_channels: 192  # 提高输出通道数以增强表达能力
  num_down_layers: 1  # 恢复为1层，提高训练速度
  num_mid_layers: 1  # 恢复为1层，提高训练速度
  num_up_layers: 1  # 恢复为1层，提高训练速度
  condition_config:
    condition_types: ['class']  # 类别条件
    class_condition_config:
      num_classes: 31  # 31个用户ID
      cond_drop_prob: 0.15  # 略微增加条件丢弃概率，帮助泛化

autoencoder_params:
  z_channels: 5  # 保持原始通道数
  codebook_size: 800  # 保持原始码书大小
  z_channels: 5  # 保持原始通道数
  codebook_size: 800  # 保持原始码书大小
  down_channels: [64, 128, 128]  # 保持原始通道配置
  mid_channels: [128, 128]
  down_sample: [True, True]
  attn_down: [False, False] 
  attn_down: [False, False] 
  norm_channels: 64
  num_heads: 16  # 增加注意力头数量，与LDM模型保持一致
  num_down_layers: 1
  num_mid_layers: 1
  num_up_layers: 1

train_params:
  seed: 1111
  task_name: '/kaggle/working/output'
  ldm_batch_size: 4  # 减小批量以适应更深的网络
  autoencoder_batch_size: 4
  ldm_acc_steps: 8  # 增加梯度累积步数以弥补批量减小
  disc_start: 500
  disc_weight: 0.8
  codebook_weight: 2.8  # 略微提高码书权重
  commitment_beta: 1.3  # 略微提高承诺损失
  perceptual_weight: 0.15  # 略微降低感知损失
  kl_weight: 0.0
  ldm_epochs: 1  # 增加训练轮数
  autoencoder_epochs: 1
  num_samples: 8
  num_grid_rows: 2
  ldm_lr: 0.00001  # 降低学习率以稳定训练
  autoencoder_lr: 0.0001
  autoencoder_acc_steps: 8
  autoencoder_img_save_steps: 8
  save_latents: True
  use_amp: False  # 混合精度训练
  cf_guidance_scale: 5.0  # 添加分类器引导尺度
  vae_latent_dir_name: 'vae_latents'
  vqvae_latent_dir_name: 'vqvae_latents'
  ldm_ckpt_name: 'ddpm_ckpt_class_cond.pth'  # 更改检查点名称
  vqvae_autoencoder_ckpt_name: 'vqvae_autoencoder_ckpt.pth'
  vae_autoencoder_ckpt_name: 'vae_autoencoder_ckpt.pth'
  vqvae_discriminator_ckpt_name: 'vqvae_discriminator_ckpt.pth'
  vae_discriminator_ckpt_name: 'vae_discriminator_ckpt.pth'
